local:
  rabbit:
    host: "localhost"
    port: 5672
    virtualHost: "/"
    connectionName: "go-rabbitmq-consumer-app"
    username: "guest"
    password: "guest"
docker:
  rabbit:
    host: "rabbitmq"
    port: 5672
    virtualHost: "/"
    connectionName: "go-rabbitmq-consumer-app"
    username: "guest"
    password: "guest"